uGFX: gos.h File Reference
gos.h File Reference
Detailed Description
GOS - Operating System Support header file.
Definition in file gos.h.
Data Structures
struct gfxSem
A semaphore.
struct gfxMutex
A mutex.
Functions
void gfxHalt (const char *msg)
Halt the GFX application due to an error.
void gfxExit (void)
Exit the GFX application.
void * gfxAlloc (size_t sz)
Allocate memory.
void * gfxRealloc (void *ptr, size_t oldsz, size_t newsz)
Re-allocate memory.
void gfxFree (void *ptr)
Free memory.
void gfxYield (void)
Yield the current thread.
void gfxSleepMilliseconds (delaytime_t ms)
Put the current thread to sleep for the specified period in milliseconds.
void gfxSleepMicroseconds (delaytime_t ms)
Put the current thread to sleep for the specified period in microseconds.
systemticks_t gfxSystemTicks (void)
Get the current operating system tick time.
systemticks_t gfxMillisecondsToTicks (delaytime_t ms)
Convert a given number of millseconds to a number of operating system ticks.
void gfxSystemLock (void)
Lock the operating system to protect a sequence of code.
void gfxSystemUnlock (void)
Unlock the operating system previous locked by gfxSystemLock()
void gfxMutexInit (gfxMutex *pmutex)
Initialise a mutex to protect a region of code from other threads.
void gfxMutexDestroy (gfxMutex *pmutex)
Destroy a Mutex.
void gfxMutexEnter (gfxMutex *pmutex)
Enter the critical code region protected by the mutex.
void gfxMutexExit (gfxMutex *pmutex)
Exit the critical code region protected by the mutex.
void gfxSemInit (gfxSem *psem, semcount_t val, semcount_t limit)
Initialise a Counted Semaphore.
void gfxSemDestroy (gfxSem *psem)
Destroy a Counted Semaphore.
bool_t gfxSemWait (gfxSem *psem, delaytime_t ms)
Wait on a semaphore.
void gfxSemSignal (gfxSem *psem)
Signal a semaphore.
void gfxSemSignalI (gfxSem *psem)
Signal a semaphore.
semcount_t gfxSemCounter (gfxSem *psem)
Get the current semaphore count.
semcount_t gfxSemCounterI (gfxSem *psem)
Get the current semaphore count.
gfxThreadHandle gfxThreadCreate (void *stackarea, size_t stacksz, threadpriority_t prio, DECLARE_THREAD_FUNCTION((*fn), p), void *param)
Start a new thread.
threadreturn_t gfxThreadWait (gfxThreadHandle thread)
Wait for a thread to finish.
gfxThreadHandle gfxThreadMe (void)
Get the current thread handle.
void gfxThreadClose (gfxThreadHandle thread)
Close the thread handle.
Macros
#define FALSE 0
Various platform (and operating system) constants.
Typedefs
typedef void * gfxThreadHandle
A thread handle.
typedef unsigned char bool_t
Various integer sizes.
#define DECLARE_THREAD_FUNCTION(fnName, param) threadreturn_t fnName(void *param)
Declare a thread stack and function.
typedef unsigned long size_t
Various platform (and operating system) dependent types.
Function Documentation
void gfxHalt (const char * msg)
Halt the GFX application due to an error.
Parameters
[in] msg An optional debug message to show (Can be NULL)
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gfxExit (void)
Exit the GFX application.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void* gfxAlloc (size_t sz)
Allocate memory.
Returns
A pointer to the memory allocated or NULL if there is no more memory available
Parameters
[in] sz The size in bytes of the area to allocate
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void* gfxRealloc (void * ptr, size_t oldsz, size_t newsz)
Re-allocate memory.
Returns
A pointer to the new memory area or NULL if there is no more memory available
Parameters
[in] ptr The old memory area to be increased/decreased in size
[in] oldsz The size in bytes of the old memory area
[in] newsz The size in bytes of the new memory area
Note
Some operating systems don't use the oldsz parameter as they implicitly know the size of old memory area. The parameter must always be supplied however for API compatibility.
gfxRealloc() can make the area smaller or larger but may have to return a different pointer. If this occurs the new area contains a copy of the data from the old area. The old memory pointer should not be used after this routine as the original area may have been freed.
If there is insufficient memory to create the new memory region, NULL is returned and the old memory area is left unchanged.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gfxFree (void * ptr)
Free memory.
Parameters
[in] ptr The memory to free
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by ginputGetMouse().
void gfxYield (void)
Yield the current thread.
Give up the rest of the current time slice for this thread in order to give other threads a chance to run.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gfxSleepMilliseconds (delaytime_t ms)
Put the current thread to sleep for the specified period in milliseconds.
Parameters
[in] ms The number milliseconds to sleep
Note
Specifying TIME_IMMEDIATE will yield the current thread but return on the next time slice.
Specifying TIME_INFINITE will sleep forever.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by ginputCalibrateMouse(), ginputGetMouseStatus(), and ginputGetToggleStatus().
void gfxSleepMicroseconds (delaytime_t ms)
Put the current thread to sleep for the specified period in microseconds.
Parameters
[in] ms The number microseconds to sleep
Note
Specifying TIME_IMMEDIATE will return immediately (no sleeping)
Specifying TIME_INFINITE will sleep forever.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
systemticks_t gfxSystemTicks (void)
Get the current operating system tick time.
Returns
The current tick time
Note
A "tick" is an arbitrary period of time that the operating system uses to mark time.
The absolute value of this call is relatively meaningless. Its usefulness is in calculating periods between two calls to this function.
As the value from this function can wrap it is important that any periods are calculated as t2 - t1 and then compared to the desired period rather than comparing t1 + period to t2
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by gtimerStart().
systemticks_t gfxMillisecondsToTicks (delaytime_t ms)
Convert a given number of millseconds to a number of operating system ticks.
Returns
The period in system ticks.
Note
A "tick" is an arbitrary period of time that the operating system uses to mark time.
Parameters
[in] ms The number of millseconds
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by gtimerStart().
void gfxSystemLock (void)
Lock the operating system to protect a sequence of code.
Note
Calling this will lock out all other threads from executing even at interrupt level within the GFX system. On hardware this may be implemented as a disabling of interrupts, however in an operating system which hides real interrupt level code it may simply use a mutex lock.
The thread MUST NOT block whilst the system is locked. It must execute in this state for as short a period as possible as this can seriously affect interrupt latency on some platforms.
While locked only interrupt level (iclass) GFX routines may be called.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gfxSystemUnlock (void)
Unlock the operating system previous locked by gfxSystemLock()
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gfxMutexInit (gfxMutex * pmutex)
Initialise a mutex to protect a region of code from other threads.
Parameters
[in] pmutex A pointer to the mutex
Note
Whilst a counting semaphore with a limit of 1 can be used for similiar purposes on many operating systems using a seperate mutex structure is more efficient.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gfxMutexDestroy (gfxMutex * pmutex)
Destroy a Mutex.
Parameters
[in] pmutex A pointer to the mutex
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gfxMutexEnter (gfxMutex * pmutex)
Enter the critical code region protected by the mutex.
Blocks until there is no other thread in the critical region.
Parameters
[in] pmutex A pointer to the mutex
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by geventAttachSource(), geventDetachSource(), geventDetachSourceListeners(), geventGetSourceListener(), geventSendEvent(), gtimerJab(), gtimerStart(), and gtimerStop().
void gfxMutexExit (gfxMutex * pmutex)
Exit the critical code region protected by the mutex.
May cause another thread waiting on the mutex to now be placed into the run queue.
Parameters
[in] pmutex A pointer to the mutex
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by geventAttachSource(), geventDetachSource(), geventDetachSourceListeners(), geventGetSourceListener(), geventSendEvent(), gtimerJab(), gtimerStart(), and gtimerStop().
void gfxSemInit (gfxSem * psem, semcount_t val, semcount_t limit)
Initialise a Counted Semaphore.
Parameters
[in] psem A pointer to the semaphore
[in] val The initial value of the semaphore
[in] limit The maxmimum value of the semaphore
Note
Operations defined for counted semaphores: Signal: The semaphore counter is increased and if the result is non-positive then a waiting thread is queued for execution. Note that once the thread reaches "limit", further signals are ignored. Wait: The semaphore counter is decreased and if the result becomes negative the thread is queued in the semaphore and suspended.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by geventListenerInit().
void gfxSemDestroy (gfxSem * psem)
Destroy a Counted Semaphore.
Parameters
[in] psem A pointer to the semaphore
Note
Any threads waiting on the semaphore will be released
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
bool_t gfxSemWait (gfxSem * psem, delaytime_t ms)
Wait on a semaphore.
The semaphore counter is decreased and if the result becomes negative the thread waits for it to become non-negative again
Returns
FALSE if the wait timeout occurred otherwise TRUE
Parameters
[in] psem A pointer to the semaphore
[in] ms The maximum time to wait for the semaphore
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by geventAttachSource(), geventDetachSource(), geventEventWait(), and geventGetSourceListener().
void gfxSemSignal (gfxSem * psem)
Signal a semaphore.
The semaphore counter is increased and if the result is non-positive then a waiting thread is queued for execution. Note that once the thread reaches "limit", further signals are ignored.
Parameters
[in] psem A pointer to the semaphore
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by geventAttachSource(), geventDetachSource(), geventGetSourceListener(), geventSendEvent(), gtimerJab(), and gtimerStart().
void gfxSemSignalI (gfxSem * psem)
Signal a semaphore.
The semaphore counter is increased and if the result is non-positive then a waiting thread is queued for execution. Note that once the thread reaches "limit", further signals are ignored.
Parameters
[in] psem A pointer to the semaphore
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by gtimerJabI().
semcount_t gfxSemCounter (gfxSem * psem)
Get the current semaphore count.
Returns
The current semaphore count
Parameters
[in] psem A pointer to the semaphore
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by geventDetachSource(), geventEventWait(), geventGetEventBuffer(), and geventSendEvent().
semcount_t gfxSemCounterI (gfxSem * psem)
Get the current semaphore count.
Returns
The current semaphore count
Parameters
[in] psem A pointer to the semaphore
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
gfxThreadHandle gfxThreadCreate (void * stackarea, size_t stacksz, threadpriority_t prio, DECLARE_THREAD_FUNCTION((*fn), p) , void * param)
Start a new thread.
Returns
Returns a thread handle if the thread was started, NULL on an error
Parameters
[in] stackarea A pointer to the area for the new threads stack or NULL to dynamically allocate it
[in] stacksz The size of the thread stack. 0 means the default operating system size although this is only valid when stackarea is dynamically allocated.
[in] prio The priority of the new thread
[in] fn The function the new thread will run
[in] param A parameter to pass the thread function.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by gtimerStart().
threadreturn_t gfxThreadWait (gfxThreadHandle thread)
Wait for a thread to finish.
Returns
Returns the thread exit code.
Parameters
[in] thread The Thread Handle
Note
This will also close the thread handle as it is no longer useful once the thread has ended.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
gfxThreadHandle gfxThreadMe (void)
Get the current thread handle.
Returns
A thread handle
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gfxThreadClose (gfxThreadHandle thread)
Close the thread handle.
Parameters
[in] thread The Thread Handle
Note
This does not affect the thread, it just closes our handle to the thread.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by gtimerStart().
Macro Definition Documentation
#define FALSE 0
Various platform (and operating system) constants.
Note
Your platform may use slightly different definitions to these
Definition at line 70 of file gos.h.
Typedef Documentation
typedef void* gfxThreadHandle
A thread handle.
Note
Your operating system will have a proper definition for this.
Definition at line 96 of file gos.h.