uGFX: Internal
Internal
GWIN
Detailed Description
Note
These definitions are normally not used by an application program. They are useful only if you want to create your own custom GWIN window or widget.
To access these definitions you must include "gwin/class_gwin.h" in your source file.
Data Structures
struct gwinVMT
The Virtual Method Table for a GWIN window.
struct gwidgetVMT
The Virtual Method Table for a widget.
struct gwmVMT
The Virtual Method Table for a window manager.
Functions
GHandle _gwindowCreate (GWindowObject *pgw, const GWindowInit *pInit, const gwinVMT *vmt, uint16_t flags)
Initialise (and allocate if necessary) the base GWIN object.
GHandle _gwidgetCreate (GWidgetObject *pgw, const GWidgetInit *pInit, const gwidgetVMT *vmt)
Initialise (and allocate if necessary) the base Widget object.
void _gwidgetDestroy (GHandle gh)
Destroy the Widget object.
void _gwidgetRedraw (GHandle gh)
Redraw the Widget object.
Variables
gfxQueueASync _GWINList
The list of all windows in the system.
GWindowManager * _GWINwm
The current window manager.
#define GWIN_FLG_DYNAMIC 0x0001
The predefined flags for a Window.
typedef struct gwinVMT gwinVMT
The Virtual Method Table for a GWIN window.
typedef struct gwidgetVMT gwidgetVMT
The Virtual Method Table for a widget.
typedef struct gwmVMT gwmVMT
The Virtual Method Table for a window manager.
Macros
#define GWIDGET_NO_INSTANCE ((uint16_t)-1)
An toggle/dial instance is not being used.
#define GWIDGET_SOURCE ((GSourceHandle)(void *)_gwidgetCreate)
The source handle that widgets use when sending events.
Function Documentation
GHandle _gwindowCreate (GWindowObject * pgw, const GWindowInit * pInit, const gwinVMT * vmt, uint16_t flags)
Initialise (and allocate if necessary) the base GWIN object.
Parameters
[in] pgw The GWindowObject structure. If NULL one is allocated from the heap
[in] pInit The user initialization parameters
[in] vmt The virtual method table for the GWIN object
[in] flags The default flags to use
Returns
The GHandle of the created window
Function Class:
Not an API, this function is for internal use only.
GHandle _gwidgetCreate (GWidgetObject * pgw, const GWidgetInit * pInit, const gwidgetVMT * vmt)
Initialise (and allocate if necessary) the base Widget object.
Parameters
[in] pgw The GWidgetObject structure. If NULL one is allocated from the heap
[in] pInit The user initialization parameters
[in] vmt The virtual method table for the Widget object
Returns
The GHandle of the created widget
Function Class:
Not an API, this function is for internal use only.
Referenced by gwinCheckboxCreate(), and gwinSliderCreate().
void _gwidgetDestroy (GHandle gh)
Destroy the Widget object.
Parameters
[in] gh The widget to destroy
Function Class:
Not an API, this function is for internal use only.
void _gwidgetRedraw (GHandle gh)
Redraw the Widget object.
Parameters
[in] gh The widget to redraw
Function Class:
Not an API, this function is for internal use only.
Referenced by gwinCheckboxCheck().
Variable Documentation
gfxQueueASync _GWINList
The list of all windows in the system.
GWindowManager* _GWINwm
The current window manager.
Macro Definition Documentation
#define GWIN_FLG_DYNAMIC 0x0001
The predefined flags for a Window.
Definition at line 30 of file class_gwin.h.
#define GWIDGET_NO_INSTANCE ((uint16_t)-1)
An toggle/dial instance is not being used.
Definition at line 60 of file class_gwin.h.
Referenced by gwinCheckboxCreate(), and gwinSliderCreate().
#define GWIDGET_SOURCE ((GSourceHandle)(void *)_gwidgetCreate)
The source handle that widgets use when sending events.
Definition at line 65 of file class_gwin.h.
Typedef Documentation
typedef struct gwinVMT gwinVMT
The Virtual Method Table for a GWIN window.
typedef struct gwidgetVMT gwidgetVMT
The Virtual Method Table for a widget.
Note
A widget must have a destroy function. Either use _gwidgetDestroy() or use your own function which internally calls _gwidgetDestroy().
A widget must have a redraw function. Use _gwidgetRedraw().
If toggleroles != 0, ToggleAssign(), ToggleGet() and one or both of ToggleOff() and ToggleOn() must be specified.
If dialroles != 0, DialAssign(), DialGet() and DialMove() must be specified.
typedef struct gwmVMT gwmVMT
The Virtual Method Table for a window manager.