uGFX: GDISP
GDISP
Detailed Description
Module to interface graphic / pixel oriented displays.
The GDISP module provides high level abstraction to interface pixel oriented graphic displays.
Precondition
GFX_USE_GDISP must be set to TRUE in gfxconf.h
Even though this is a software emulation of a low level driver most validation doesn't need to happen here as eventually we call a real low level driver routine and if validation is required - it will do it.
Data Structures
struct point_t
Type for a 2D point on the screen.
Modules
Image
Functions
bool_t gdispIsBusy (void)
Test if the GDISP engine is currently drawing.
void gdispClear (color_t color)
Clear the display to the specified color.
void gdispDrawPixel (coord_t x, coord_t y, color_t color)
Set a pixel in the specified color.
void gdispDrawLine (coord_t x0, coord_t y0, coord_t x1, coord_t y1, color_t color)
Draw a line.
void gdispFillArea (coord_t x, coord_t y, coord_t cx, coord_t cy, color_t color)
Fill an area with a color.
void gdispBlitAreaEx (coord_t x, coord_t y, coord_t cx, coord_t cy, coord_t srcx, coord_t srcy, coord_t srccx, const pixel_t *buffer)
Fill an area using the supplied bitmap.
void gdispSetClip (coord_t x, coord_t y, coord_t cx, coord_t cy)
Clip all drawing to the defined area.
void gdispDrawCircle (coord_t x, coord_t y, coord_t radius, color_t color)
Draw a circle.
void gdispFillCircle (coord_t x, coord_t y, coord_t radius, color_t color)
Draw a filled circle.
void gdispDrawEllipse (coord_t x, coord_t y, coord_t a, coord_t b, color_t color)
Draw an ellipse.
void gdispFillEllipse (coord_t x, coord_t y, coord_t a, coord_t b, color_t color)
Draw a filled ellipse.
color_t gdispGetPixelColor (coord_t x, coord_t y)
Get the color of a pixel.
void gdispVerticalScroll (coord_t x, coord_t y, coord_t cx, coord_t cy, int lines, color_t bgcolor)
Scroll vertically a section of the screen.
void gdispControl (unsigned what, void *value)
Control hardware specific parts of the display. eg powermodes, backlight etc.
void * gdispQuery (unsigned what)
Query a property of the display.
void gdispDrawBox (coord_t x, coord_t y, coord_t cx, coord_t cy, color_t color)
Draw a rectangular box.
void gdispDrawPoly (coord_t tx, coord_t ty, const point *pntarray, unsigned cnt, color_t color)
Draw an enclosed polygon (convex, non-convex or complex).
void gdispFillConvexPoly (coord_t tx, coord_t ty, const point *pntarray, unsigned cnt, color_t color)
Fill a convex polygon.
void gdispDrawChar (coord_t x, coord_t y, uint16_t c, font_t font, color_t color)
Draw a text character.
void gdispFillChar (coord_t x, coord_t y, uint16_t c, font_t font, color_t color, color_t bgcolor)
Draw a text character with a filled background.
void gdispDrawString (coord_t x, coord_t y, const char *str, font_t font, color_t color)
Draw a text string.
void gdispFillString (coord_t x, coord_t y, const char *str, font_t font, color_t color, color_t bgcolor)
Draw a text string.
void gdispDrawStringBox (coord_t x, coord_t y, coord_t cx, coord_t cy, const char *str, font_t font, color_t color, justify_t justify)
Draw a text string vertically centered within the specified box.
void gdispFillStringBox (coord_t x, coord_t y, coord_t cx, coord_t cy, const char *str, font_t font, color_t color, color_t bgColor, justify_t justify)
Draw a text string vertically centered within the specified box. The box background is filled with the specified background color.
coord_t gdispGetFontMetric (font_t font, fontmetric_t metric)
Get a metric of a font.
coord_t gdispGetCharWidth (char c, font_t font)
Get the pixel width of a character.
coord_t gdispGetStringWidth (const char *str, font_t font)
Get the pixel width of a string.
font_t gdispOpenFont (const char *name)
Find a font and return it.
void gdispCloseFont (font_t font)
Release a font after use.
font_t gdispScaleFont (font_t font, uint8_t scale_x, uint8_t scale_y)
Make a scaled copy of an existing font.
const char * gdispGetFontName (font_t font)
Get the name of the specified font.
void gdispDrawRoundedBox (coord_t x, coord_t y, coord_t cx, coord_t cy, coord_t radius, color_t color)
Draw a rectangular box with rounded corners.
void gdispFillRoundedBox (coord_t x, coord_t y, coord_t cx, coord_t cy, coord_t radius, color_t color)
Draw a filled rectangular box with rounded corners.
color_t gdispBlendColor (color_t fg, color_t bg, uint8_t alpha)
Blend 2 colors according to the alpha.
void gdispPackPixels (const pixel_t *buf, coord_t cx, coord_t x, coord_t y, color_t color)
Pack a pixel into a pixel buffer.
Some basic colors
#define White HTML2COLOR(0xFFFFFF)
#define Black HTML2COLOR(0x000000)
#define Gray HTML2COLOR(0x808080)
#define Grey Gray
#define Blue HTML2COLOR(0x0000FF)
#define Red HTML2COLOR(0xFF0000)
#define Fuchsia HTML2COLOR(0xFF00FF)
#define Magenta Fuchsia
#define Green HTML2COLOR(0x008000)
#define Yellow HTML2COLOR(0xFFFF00)
#define Aqua HTML2COLOR(0x00FFFF)
#define Cyan Aqua
#define Lime HTML2COLOR(0x00FF00)
#define Maroon HTML2COLOR(0x800000)
#define Navy HTML2COLOR(0x000080)
#define Olive HTML2COLOR(0x808000)
#define Purple HTML2COLOR(0x800080)
#define Silver HTML2COLOR(0xC0C0C0)
#define Teal HTML2COLOR(0x008080)
#define Orange HTML2COLOR(0xFFA500)
#define Pink HTML2COLOR(0xFFC0CB)
#define SkyBlue HTML2COLOR(0x87CEEB)
GDISP hardware accelerated support
#define GDISP_HARDWARE_LINES FALSE
Hardware accelerated line drawing.
#define GDISP_HARDWARE_CLEARS FALSE
Hardware accelerated screen clears.
#define GDISP_HARDWARE_FILLS FALSE
Hardware accelerated rectangular fills.
#define GDISP_HARDWARE_BITFILLS FALSE
Hardware accelerated fills from an image.
#define GDISP_HARDWARE_CIRCLES FALSE
Hardware accelerated circles.
#define GDISP_HARDWARE_CIRCLEFILLS FALSE
Hardware accelerated filled circles.
#define GDISP_HARDWARE_ELLIPSES FALSE
Hardware accelerated ellipses.
#define GDISP_HARDWARE_ELLIPSEFILLS FALSE
Hardware accelerated filled ellipses.
#define GDISP_HARDWARE_ARCS FALSE
Hardware accelerated arc's.
#define GDISP_HARDWARE_ARCFILLS FALSE
Hardware accelerated filled arcs.
#define GDISP_HARDWARE_SCROLL FALSE
Hardware accelerated scrolling.
#define GDISP_HARDWARE_PIXELREAD FALSE
Reading back of pixel values.
#define GDISP_HARDWARE_CONTROL FALSE
The driver supports one or more control commands.
#define GDISP_HARDWARE_QUERY FALSE
The driver supports a non-standard query.
#define GDISP_HARDWARE_CLIP FALSE
The driver supports a clipping in hardware.
GDISP pixel format choices
#define GDISP_PIXELFORMAT GDISP_PIXELFORMAT_ERROR
The native pixel format for this device.
#define GDISP_PACKED_PIXELS FALSE
Do pixels require packing for a blit.
#define GDISP_PACKED_LINES FALSE
Do lines of pixels require packing for a blit.
GDISP Functionality to be included
#define GDISP_THREAD_PRIORITY NORMAL_PRIORITY
The priority of the GDISP thread.
#define GDISP_NEED_VALIDATION TRUE
Should all operations be clipped to the screen and colors validated.
#define GDISP_NEED_CLIP TRUE
Are clipping functions needed.
#define GDISP_NEED_TEXT FALSE
Are text functions needed.
#define GDISP_NEED_CIRCLE TRUE
Are circle functions needed.
#define GDISP_NEED_ELLIPSE FALSE
Are ellipse functions needed.
#define GDISP_NEED_ARC FALSE
Are arc functions needed.
#define GDISP_NEED_CONVEX_POLYGON FALSE
Are convex polygon functions needed.
#define GDISP_NEED_SCROLL FALSE
Are scrolling functions needed.
#define GDISP_NEED_PIXELREAD FALSE
Is the capability to read pixels back needed.
#define GDISP_NEED_CONTROL FALSE
Control some aspect of the hardware operation.
#define GDISP_NEED_QUERY FALSE
Query some aspect of the hardware operation.
#define GDISP_NEED_IMAGE FALSE
Is the image interface required.
#define GDISP_NEED_MSGAPI FALSE
Is the messaging api interface required.
GDISP Image Options
Precondition
GDISP_NEED_IMAGE must be TRUE
#define GDISP_NEED_IMAGE_NATIVE FALSE
Is native image decoding required.
#define GDISP_NEED_IMAGE_GIF FALSE
Is GIF image decoding required.
#define GDISP_NEED_IMAGE_BMP FALSE
Is BMP image decoding required.
#define GDISP_NEED_IMAGE_JPG FALSE
Is JPG image decoding required.
#define GDISP_NEED_IMAGE_PNG FALSE
Is PNG image decoding required.
#define GDISP_NEED_IMAGE_ACCOUNTING FALSE
Is memory accounting required during image decoding.
GDISP Text Rendering Options
#define GDISP_NEED_UTF8 FALSE
Enable UTF-8 support for text rendering.
#define GDISP_NEED_TEXT_KERNING FALSE
Enable kerning for font rendering (improves character placement).
#define GDISP_NEED_ANTIALIAS FALSE
Enable antialiased font support.
GDISP Multi-Threading Options
#define GDISP_NEED_MULTITHREAD FALSE
Do the drawing functions need to be thread-safe.
#define GDISP_NEED_ASYNC FALSE
Use asynchronous calls (multi-thread safe).
GDISP Optional Low Level Driver Defines
#define GDISP_USE_CUSTOM_BOARD FALSE
Use a custom board definition even if a board definition exists.
Macros
#define GDISP_CMD_PORT GPIOC
The GPIO pin config.
#define GDISP_CONTROL_POWER 0
Driver Control Constants.
#define GDISP_QUERY_LLD 1000
Driver Query Constants.
#define GDISP_PIXELFORMAT_MONO 1
Driver Pixel Format Constants.
#define COLOR(c) ((color_t)(c))
Convert a number (of any type) to a color_t.
#define MASKCOLOR FALSE
Does the color_t type contain invalid bits that need masking.
#define RGB2COLOR(r, g, b) ((color_t)((((r) & 0xF8)<<8) | (((g) & 0xFC)<<3) | (((b) & 0xF8)>>3)))
Convert red, green, blue (each 0 to 255) into a color value.
#define HTML2COLOR(h) ((color_t)((((h) & 0xF80000)>>8) | (((h) & 0x00FC00)>>5) | (((h) & 0x0000F8)>>3)))
Convert a 6 digit HTML code (hex) into a color value.
#define RED_OF(c) (((c) & 0xF800)>>8)
Extract the red component (0 to 255) of a color value.
#define GREEN_OF(c) (((c)&0x007E)>>3)
Extract the green component (0 to 255) of a color value.
#define BLUE_OF(c) (((c)&0x001F)<<3)
Extract the blue component (0 to 255) of a color value.
#define gdispSetPowerMode(powerMode) gdispControl(GDISP_CONTROL_POWER, (void *)(unsigned)(powerMode))
Set the display power mode.
#define gdispSetOrientation(newOrientation) gdispControl(GDISP_CONTROL_ORIENTATION, (void *)(unsigned)(newOrientation))
Set the display orientation.
#define gdispSetBacklight(percent) gdispControl(GDISP_CONTROL_BACKLIGHT, (void *)(unsigned)(percent))
Set the display backlight.
#define gdispSetContrast(percent) gdispControl(GDISP_CONTROL_CONTRAST, (void *)(unsigned)(percent))
Set the display contrast.
#define gdispGetWidth() (GDISP.Width)
Get the display width in pixels.
#define gdispGetHeight() (GDISP.Height)
Get the display height in pixels.
#define gdispGetPowerMode() (GDISP.Powermode)
Get the current display power mode.
#define gdispGetOrientation() (GDISP.Orientation)
Get the current display orientation.
#define gdispGetBacklight() (GDISP.Backlight)
Get the current display backlight brightness.
#define gdispGetContrast() (GDISP.Contrast)
Get the current display contrast.
#define gdispUnsetClip() gdispSetClip(0,0,gdispGetWidth(),gdispGetHeight())
Reset the clip area to the full screen.
Typedefs
typedef int16_t coord_t
The type for a coordinate or length on the screen.
typedef struct point_t point
Type for a 2D point on the screen.
typedef enum justify justify_t
Type for the text justification.
typedef enum fontmetric fontmetric_t
Type for the font metric.
typedef struct mf_font_s * font_t
The type of a font.
typedef enum orientation gdisp_orientation_t
Type for the screen orientation.
typedef enum powermode gdisp_powermode_t
Type for the available power modes for the screen.
typedef uint16_t color_t
The color of a pixel.
typedef color_t pixel_t
The type of a pixel.
Enumerations
enum justify
Type for the text justification.
enum fontmetric
Type for the font metric.
enum orientation
Type for the screen orientation.
enum powermode
Type for the available power modes for the screen.
Function Documentation
bool_t gdispIsBusy (void)
Test if the GDISP engine is currently drawing.
Note
This function will always return FALSE if GDISP_NEED_ASYNC is not defined.
Returns
TRUE if gdisp is busy, FALSE otherwise
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gdispClear (color_t color)
Clear the display to the specified color.
Parameters
[in] color The color to use when clearing the screen
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by gfxInit(), and ginputCalibrateMouse().
void gdispDrawPixel (coord_t x, coord_t y, color_t color)
Set a pixel in the specified color.
Parameters
[in] x,y The position to set the pixel.
[in] color The color to use
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gdispDrawLine (coord_t x0, coord_t y0, coord_t x1, coord_t y1, color_t color)
Draw a line.
Parameters
[in] x0,y0 The start position
[in] x1,y1 The end position
[in] color The color to use
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by gwinSliderDraw_Std().
void gdispFillArea (coord_t x, coord_t y, coord_t cx, coord_t cy, color_t color)
Fill an area with a color.
Parameters
[in] x,y The start position
[in] cx,cy The size of the box (outside dimensions)
[in] color The color to use
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by ginputCalibrateMouse(), gwinCheckboxDraw_CheckOnLeft(), and gwinSliderDraw_Std().
void gdispBlitAreaEx (coord_t x, coord_t y, coord_t cx, coord_t cy, coord_t srcx, coord_t srcy, coord_t srccx, const pixel_t * buffer)
Fill an area using the supplied bitmap.
The bitmap is in the pixel format specified by the low level driver
Note
If a packed pixel format is used and the width doesn't match a whole number of bytes, the next line will start on a non-byte boundary (no end-of-line padding).
If GDISP_NEED_ASYNC is defined then the buffer must be static or at least retained until this call has finished the blit. You can tell when all graphics drawing is finished by gdispIsBusy() going FALSE.
Parameters
[in] x,y The start position
[in] cx,cy The size of the filled area
[in] srcx,srcy The bitmap position to start the fill form
[in] srccx The width of a line in the bitmap
[in] buffer The bitmap in the driver's pixel format
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gdispSetClip (coord_t x, coord_t y, coord_t cx, coord_t cy)
Clip all drawing to the defined area.
Parameters
[in] x,y The start position
[in] cx,cy The size of the clip area
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by ginputCalibrateMouse().
void gdispDrawCircle (coord_t x, coord_t y, coord_t radius, color_t color)
Draw a circle.
Parameters
[in] x,y The center of the circle
[in] radius The radius of the circle
[in] color The color to use
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gdispFillCircle (coord_t x, coord_t y, coord_t radius, color_t color)
Draw a filled circle.
Parameters
[in] x,y The center of the circle
[in] radius The radius of the circle
[in] color The color to use
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gdispDrawEllipse (coord_t x, coord_t y, coord_t a, coord_t b, color_t color)
Draw an ellipse.
Parameters
[in] x,y The center of the ellipse
[in] a,b The dimensions of the ellipse
[in] color The color to use
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gdispFillEllipse (coord_t x, coord_t y, coord_t a, coord_t b, color_t color)
Draw a filled ellipse.
Parameters
[in] x,y The center of the ellipse
[in] a,b The dimensions of the ellipse
[in] color The color to use
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
color_t gdispGetPixelColor (coord_t x, coord_t y)
Get the color of a pixel.
Returns
The color of the pixel.
Parameters
[in] x,y The position of the pixel
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gdispVerticalScroll (coord_t x, coord_t y, coord_t cx, coord_t cy, int lines, color_t bgcolor)
Scroll vertically a section of the screen.
Precondition
GDISP_NEED_SCROLL must be set to TRUE in gfxconf.h
Note
Optional.
If lines is >= cy, it is equivelent to a area fill with bgcolor.
Parameters
[in] x,y The start of the area to be scrolled
[in] cx,cy The size of the area to be scrolled
[in] lines The number of lines to scroll (Can be positive or negative)
[in] bgcolor The color to fill the newly exposed area.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gdispControl (unsigned what, void * value)
Control hardware specific parts of the display. eg powermodes, backlight etc.
Note
Depending on the hardware implementation this function may not support some codes. They will be ignored.
Parameters
[in] what what you want to control
[in] value The value to be assigned
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void* gdispQuery (unsigned what)
Query a property of the display.
Note
The result must be typecast to the correct type.
An unsupported query will return (void *)-1.
Parameters
[in] what What to query
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gdispDrawBox (coord_t x, coord_t y, coord_t cx, coord_t cy, color_t color)
Draw a rectangular box.
Parameters
[in] x,y The start position
[in] cx,cy The size of the box (outside dimensions)
[in] color The color to use
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by gwinCheckboxDraw_CheckOnLeft(), and gwinSliderDraw_Std().
void gdispDrawPoly (coord_t tx, coord_t ty, const point * pntarray, unsigned cnt, color_t color)
Draw an enclosed polygon (convex, non-convex or complex).
Parameters
[in] tx,ty Transform all points in pntarray by tx, ty
[in] pntarray An array of points
[in] cnt The number of points in the array
[in] color The color to use
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gdispFillConvexPoly (coord_t tx, coord_t ty, const point * pntarray, unsigned cnt, color_t color)
Fill a convex polygon.
Doesn't handle non-convex or complex polygons.
Parameters
[in] tx,ty Transform all points in pntarray by tx, ty
[in] pntarray An array of points
[in] cnt The number of points in the array
[in] color The color to use
Note
Convex polygons are those that have no internal angles. That is; you can draw a line from any point on the polygon to any other point on the polygon without it going outside the polygon. In our case we generalise this a little by saying that an infinite horizontal line (at any y value) will cross no more than two edges on the polygon. Some non-convex polygons do fit this criteria and can therefore be drawn.
This routine is designed to be very efficient with even simple display hardware.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gdispDrawChar (coord_t x, coord_t y, uint16_t c, font_t font, color_t color)
Draw a text character.
Parameters
[in] x,y The position for the text
[in] c The character to draw
[in] font The font to use
[in] color The color to use
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gdispFillChar (coord_t x, coord_t y, uint16_t c, font_t font, color_t color, color_t bgcolor)
Draw a text character with a filled background.
Parameters
[in] x,y The position for the text
[in] c The character to draw
[in] font The font to use
[in] color The color to use
[in] bgcolor The background color to use
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gdispDrawString (coord_t x, coord_t y, const char * str, font_t font, color_t color)
Draw a text string.
Parameters
[in] x,y The position for the text
[in] font The font to use
[in] str The string to draw
[in] color The color to use
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gdispFillString (coord_t x, coord_t y, const char * str, font_t font, color_t color, color_t bgcolor)
Draw a text string.
Parameters
[in] x,y The position for the text
[in] str The string to draw
[in] font The font to use
[in] color The color to use
[in] bgcolor The background color to use
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gdispDrawStringBox (coord_t x, coord_t y, coord_t cx, coord_t cy, const char * str, font_t font, color_t color, justify_t justify)
Draw a text string vertically centered within the specified box.
Parameters
[in] x,y The position for the text (need to define top-right or base-line - check code)
[in] cx,cy The width and height of the box
[in] str The string to draw
[in] font The font to use
[in] color The color to use
[in] justify Justify the text left, center or right within the box
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by gwinSliderDraw_Std().
void gdispFillStringBox (coord_t x, coord_t y, coord_t cx, coord_t cy, const char * str, font_t font, color_t color, color_t bgColor, justify_t justify)
Draw a text string vertically centered within the specified box. The box background is filled with the specified background color.
Note
The entire box is filled
Parameters
[in] x,y The position for the text (need to define top-right or base-line - check code)
[in] cx,cy The width and height of the box
[in] str The string to draw
[in] font The font to use
[in] color The color to use
[in] bgColor The background color to use
[in] justify Justify the text left, center or right within the box
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by ginputCalibrateMouse(), and gwinCheckboxDraw_CheckOnLeft().
coord_t gdispGetFontMetric (font_t font, fontmetric_t metric)
Get a metric of a font.
Returns
The metric requested in pixels.
Parameters
[in] font The font to test
[in] metric The metric to measure
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
coord_t gdispGetCharWidth (char c, font_t font)
Get the pixel width of a character.
Returns
The width of the character in pixels. Does not include any between character padding.
Parameters
[in] c The character to draw
[in] font The font to use
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
coord_t gdispGetStringWidth (const char * str, font_t font)
Get the pixel width of a string.
Returns
The width of the string in pixels.
Parameters
[in] str The string to measure
[in] font The font to use
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
font_t gdispOpenFont (const char * name)
Find a font and return it.
The supplied name is matched against the font name. A '*' will replace 0 or more characters.
Returns
Returns a font or NULL if no matching font could be found.
Parameters
[in] name The font name to find.
Note
Wildcard matching will match the shortest possible match.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by ginputCalibrateMouse().
void gdispCloseFont (font_t font)
Release a font after use.
Parameters
[in] font The font to release.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by ginputCalibrateMouse().
font_t gdispScaleFont (font_t font, uint8_t scale_x, uint8_t scale_y)
Make a scaled copy of an existing font.
Allocates memory for new font metadata using gfxAlloc, remember to close font after use!
Returns
A new font or NULL if out of memory.
Parameters
[in] font The base font to use.
[in] scale_x The scale factor in horizontal direction.
[in] scale_y The scale factor in vertical direction.
const char* gdispGetFontName (font_t font)
Get the name of the specified font.
Returns
The name of the font.
Parameters
[in] font The font to get the name for.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gdispDrawRoundedBox (coord_t x, coord_t y, coord_t cx, coord_t cy, coord_t radius, color_t color)
Draw a rectangular box with rounded corners.
Parameters
[in] x,y The start position
[in] cx,cy The size of the box (outside dimensions)
[in] radius The radius of the rounded corners
[in] color The color to use
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gdispFillRoundedBox (coord_t x, coord_t y, coord_t cx, coord_t cy, coord_t radius, color_t color)
Draw a filled rectangular box with rounded corners.
Parameters
[in] x,y The start position
[in] cx,cy The size of the box (outside dimensions)
[in] radius The radius of the rounded corners
[in] color The color to use
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
color_t gdispBlendColor (color_t fg, color_t bg, uint8_t alpha)
Blend 2 colors according to the alpha.
Returns
The combined color
Parameters
[in] fg The foreground color
[in] bg The background color
[in] alpha The alpha value (0-255). 0 is all background, 255 is all foreground.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gdispPackPixels (const pixel_t * buf, coord_t cx, coord_t x, coord_t y, color_t color)
Pack a pixel into a pixel buffer.
Note
This function performs no buffer boundary checking regardless of whether GDISP_NEED_CLIP has been specified.
Parameters
[in] buf The buffer to put the pixel in
[in] cx The width of a pixel line
[in] x,y The location of the pixel to place
[in] color The color to put into the buffer
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Macro Definition Documentation
#define GDISP_CMD_PORT GPIOC
The GPIO pin config.
This block of defines tell your driver how you wired your display controller to your MCU. Please change them accordingly.
Definition at line 28 of file gdisp_lld_board_example_gpio.h.
#define GDISP_CONTROL_POWER 0
Driver Control Constants.
Unsupported control codes are ignored.
Note
The value parameter should always be typecast to (void *).
There are some predefined and some specific to the low level driver.
GDISP_CONTROL_POWER - Takes a gdisp_powermode_t GDISP_CONTROL_ORIENTATION - Takes a gdisp_orientation_t GDISP_CONTROL_BACKLIGHT - Takes an int from 0 to 100. For a driver that only supports off/on anything other than zero is on. GDISP_CONTROL_CONTRAST - Takes an int from 0 to 100. GDISP_CONTROL_LLD - Low level driver control constants start at this value.
Definition at line 112 of file gdisp.h.
#define GDISP_QUERY_LLD 1000
Driver Query Constants.
Unsupported query codes return (void *)-1.
Note
The result should be typecast the required type.
GDISP_QUERY_LLD - Low level driver control constants start at this value.
Definition at line 125 of file gdisp.h.
#define GDISP_PIXELFORMAT_MONO 1
Driver Pixel Format Constants.
Definition at line 130 of file gdisp.h.
#define COLOR (c) ((color_t)(c))
Convert a number (of any type) to a color_t.
Masks any invalid bits in the color
Definition at line 180 of file gdisp.h.
#define MASKCOLOR FALSE
Does the color_t type contain invalid bits that need masking.
Definition at line 184 of file gdisp.h.
#define RGB2COLOR (r, g, b) ((color_t)((((r) & 0xF8)<<8) | (((g) & 0xFC)<<3) | (((b) & 0xF8)>>3)))
Convert red, green, blue (each 0 to 255) into a color value.
Definition at line 188 of file gdisp.h.
#define HTML2COLOR (h) ((color_t)((((h) & 0xF80000)>>8) | (((h) & 0x00FC00)>>5) | (((h) & 0x0000F8)>>3)))
Convert a 6 digit HTML code (hex) into a color value.
Definition at line 192 of file gdisp.h.
#define RED_OF (c) (((c) & 0xF800)>>8)
Extract the red component (0 to 255) of a color value.
Definition at line 196 of file gdisp.h.
#define GREEN_OF (c) (((c)&0x007E)>>3)
Extract the green component (0 to 255) of a color value.
Definition at line 200 of file gdisp.h.
#define BLUE_OF (c) (((c)&0x001F)<<3)
Extract the blue component (0 to 255) of a color value.
Definition at line 204 of file gdisp.h.
#define gdispSetPowerMode (powerMode) gdispControl(GDISP_CONTROL_POWER, (void *)(unsigned)(powerMode))
Set the display power mode.
Note
Ignored if not supported by the display.
Parameters
[in] powerMode The new power mode
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 853 of file gdisp.h.
#define gdispSetOrientation (newOrientation) gdispControl(GDISP_CONTROL_ORIENTATION, (void *)(unsigned)(newOrientation))
Set the display orientation.
Note
Ignored if not supported by the display.
Parameters
[in] newOrientation The new orientation
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 863 of file gdisp.h.
Referenced by ginputCalibrateMouse().
#define gdispSetBacklight (percent) gdispControl(GDISP_CONTROL_BACKLIGHT, (void *)(unsigned)(percent))
Set the display backlight.
Note
Ignored if not supported by the display.
Parameters
[in] percent The new brightness (0 - 100%)
Note
For displays that only support backlight off and on, 0 = off, anything else = on
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 876 of file gdisp.h.
#define gdispSetContrast (percent) gdispControl(GDISP_CONTROL_CONTRAST, (void *)(unsigned)(percent))
Set the display contrast.
Note
Ignored if not supported by the display.
Parameters
[in] percent The new contrast (0 - 100%)
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 886 of file gdisp.h.
#define gdispGetWidth () (GDISP.Width)
Get the display width in pixels.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 893 of file gdisp.h.
Referenced by ginputCalibrateMouse().
#define gdispGetHeight () (GDISP.Height)
Get the display height in pixels.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 900 of file gdisp.h.
Referenced by ginputCalibrateMouse().
#define gdispGetPowerMode () (GDISP.Powermode)
Get the current display power mode.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 907 of file gdisp.h.
#define gdispGetOrientation () (GDISP.Orientation)
Get the current display orientation.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 914 of file gdisp.h.
#define gdispGetBacklight () (GDISP.Backlight)
Get the current display backlight brightness.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 921 of file gdisp.h.
#define gdispGetContrast () (GDISP.Contrast)
Get the current display contrast.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 928 of file gdisp.h.
#define gdispUnsetClip () gdispSetClip(0,0,gdispGetWidth(),gdispGetHeight())
Reset the clip area to the full screen.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 937 of file gdisp.h.
#define GDISP_HARDWARE_LINES FALSE
Hardware accelerated line drawing.
If set to FALSE software emulation is used.
Definition at line 34 of file gdisp_lld.h.
#define GDISP_HARDWARE_CLEARS FALSE
Hardware accelerated screen clears.
If set to FALSE software emulation is used.
Definition at line 42 of file gdisp_lld.h.
#define GDISP_HARDWARE_FILLS FALSE
Hardware accelerated rectangular fills.
If set to FALSE software emulation is used.
Definition at line 50 of file gdisp_lld.h.
#define GDISP_HARDWARE_BITFILLS FALSE
Hardware accelerated fills from an image.
If set to FALSE software emulation is used.
Definition at line 58 of file gdisp_lld.h.
#define GDISP_HARDWARE_CIRCLES FALSE
Hardware accelerated circles.
If set to FALSE software emulation is used.
Definition at line 66 of file gdisp_lld.h.
#define GDISP_HARDWARE_CIRCLEFILLS FALSE
Hardware accelerated filled circles.
If set to FALSE software emulation is used.
Definition at line 74 of file gdisp_lld.h.
#define GDISP_HARDWARE_ELLIPSES FALSE
Hardware accelerated ellipses.
If set to FALSE software emulation is used.
Definition at line 82 of file gdisp_lld.h.
#define GDISP_HARDWARE_ELLIPSEFILLS FALSE
Hardware accelerated filled ellipses.
If set to FALSE software emulation is used.
Definition at line 90 of file gdisp_lld.h.
#define GDISP_HARDWARE_ARCS FALSE
Hardware accelerated arc's.
If set to FALSE software emulation is used.
Definition at line 98 of file gdisp_lld.h.
#define GDISP_HARDWARE_ARCFILLS FALSE
Hardware accelerated filled arcs.
If set to FALSE software emulation is used.
Definition at line 106 of file gdisp_lld.h.
#define GDISP_HARDWARE_SCROLL FALSE
Hardware accelerated scrolling.
If set to FALSE there is no support for scrolling.
Definition at line 114 of file gdisp_lld.h.
#define GDISP_HARDWARE_PIXELREAD FALSE
Reading back of pixel values.
If set to FALSE there is no support for pixel read-back.
Definition at line 122 of file gdisp_lld.h.
#define GDISP_HARDWARE_CONTROL FALSE
The driver supports one or more control commands.
If set to FALSE there is no support for control commands.
Definition at line 130 of file gdisp_lld.h.
#define GDISP_HARDWARE_QUERY FALSE
The driver supports a non-standard query.
If set to FALSE there is no support for non-standard queries.
Definition at line 138 of file gdisp_lld.h.
#define GDISP_HARDWARE_CLIP FALSE
The driver supports a clipping in hardware.
If set to FALSE there is no support for non-standard queries.
Definition at line 146 of file gdisp_lld.h.
#define GDISP_PIXELFORMAT GDISP_PIXELFORMAT_ERROR
The native pixel format for this device.
Note
Should be set to one of the following: GDISP_PIXELFORMAT_RGB565 GDISP_PIXELFORMAT_RGB888 GDISP_PIXELFORMAT_RGB444 GDISP_PIXELFORMAT_RGB332 GDISP_PIXELFORMAT_RGB666 GDISP_PIXELFORMAT_CUSTOM
If you set GDISP_PIXELFORMAT_CUSTOM you need to also define color_t, RGB2COLOR(r,g,b), HTML2COLOR(h), RED_OF(c), GREEN_OF(c), BLUE_OF(c), COLOR(c) and MASKCOLOR.
Definition at line 175 of file gdisp_lld.h.
#define GDISP_PACKED_PIXELS FALSE
Do pixels require packing for a blit.
Note
Is only valid for a pixel format that doesn't fill it's datatype. ie formats: GDISP_PIXELFORMAT_RGB888 GDISP_PIXELFORMAT_RGB444 GDISP_PIXELFORMAT_RGB666 GDISP_PIXELFORMAT_CUSTOM
If you use GDISP_PIXELFORMAT_CUSTOM and packed bit fills you need to also define gdispPackPixels(buf,cx,x,y,c)
If you are using GDISP_HARDWARE_BITFILLS = FALSE then the pixel format must not be a packed format as the software blit does not support packed pixels
Very few cases should actually require packed pixels as the low level driver can also pack on the fly as it is sending it to the graphics device.
Definition at line 195 of file gdisp_lld.h.
#define GDISP_PACKED_LINES FALSE
Do lines of pixels require packing for a blit.
Note
Ignored if GDISP_PACKED_PIXELS is FALSE
Definition at line 203 of file gdisp_lld.h.
#define GDISP_THREAD_PRIORITY NORMAL_PRIORITY
The priority of the GDISP thread.
Defaults to NORMAL_PRIORITY
Definition at line 28 of file gdisp/options.h.
#define GDISP_NEED_VALIDATION TRUE
Should all operations be clipped to the screen and colors validated.
Defaults to TRUE.
Note
If this is FALSE, any operations that extend beyond the edge of the screen will have undefined results. Any out-of-range colors will produce undefined results.
If defined then all low level and high level GDISP driver routines must check the validity of inputs and do something sensible if they are out of range. It doesn't have to be efficient, just valid.
Definition at line 42 of file gdisp/options.h.
#define GDISP_NEED_CLIP TRUE
Are clipping functions needed.
Defaults to TRUE
Definition at line 49 of file gdisp/options.h.
#define GDISP_NEED_TEXT FALSE
Are text functions needed.
Defaults to FALSE
Definition at line 56 of file gdisp/options.h.
#define GDISP_NEED_CIRCLE TRUE
Are circle functions needed.
Defaults to TRUE
Definition at line 63 of file gdisp/options.h.
#define GDISP_NEED_ELLIPSE FALSE
Are ellipse functions needed.
Defaults to FALSE
Definition at line 70 of file gdisp/options.h.
#define GDISP_NEED_ARC FALSE
Are arc functions needed.
Defaults to FALSE
Note
Requires the maths library to be included in the link. ie -lm
Definition at line 78 of file gdisp/options.h.
#define GDISP_NEED_CONVEX_POLYGON FALSE
Are convex polygon functions needed.
Defaults to FALSE
Note
Convex polygons are those that have no internal angles. That is; you can draw a line from any point on the polygon to any other point on the polygon without it going outside the polygon.
Definition at line 88 of file gdisp/options.h.
#define GDISP_NEED_SCROLL FALSE
Are scrolling functions needed.
Defaults to FALSE
Note
This function must be supported by the low level GDISP driver you have included in your project. If it isn't, defining this option will cause a compile error.
Definition at line 98 of file gdisp/options.h.
#define GDISP_NEED_PIXELREAD FALSE
Is the capability to read pixels back needed.
Defaults to FALSE
Note
This function must be supported by the low level GDISP driver you have included in your project. If it isn't, defining this option will cause a compile error.
Definition at line 108 of file gdisp/options.h.
#define GDISP_NEED_CONTROL FALSE
Control some aspect of the hardware operation.
Defaults to FALSE
Note
This allows control of hardware specific features such as screen rotation, backlight levels, contrast etc
Definition at line 117 of file gdisp/options.h.
#define GDISP_NEED_QUERY FALSE
Query some aspect of the hardware operation.
Defaults to FALSE
Note
This allows query of hardware specific features
Definition at line 125 of file gdisp/options.h.
#define GDISP_NEED_IMAGE FALSE
Is the image interface required.
Defaults to FALSE
Definition at line 132 of file gdisp/options.h.
#define GDISP_NEED_MSGAPI FALSE
Is the messaging api interface required.
Defaults to FALSE
Definition at line 139 of file gdisp/options.h.
#define GDISP_NEED_IMAGE_NATIVE FALSE
Is native image decoding required.
Defaults to FALSE
Definition at line 153 of file gdisp/options.h.
#define GDISP_NEED_IMAGE_GIF FALSE
Is GIF image decoding required.
Defaults to FALSE
Definition at line 160 of file gdisp/options.h.
#define GDISP_NEED_IMAGE_BMP FALSE
Is BMP image decoding required.
Defaults to FALSE
Definition at line 167 of file gdisp/options.h.
#define GDISP_NEED_IMAGE_JPG FALSE
Is JPG image decoding required.
Defaults to FALSE
Definition at line 174 of file gdisp/options.h.
#define GDISP_NEED_IMAGE_PNG FALSE
Is PNG image decoding required.
Defaults to FALSE
Definition at line 181 of file gdisp/options.h.
#define GDISP_NEED_IMAGE_ACCOUNTING FALSE
Is memory accounting required during image decoding.
Defaults to FALSE
Definition at line 188 of file gdisp/options.h.
#define GDISP_NEED_UTF8 FALSE
Enable UTF-8 support for text rendering.
Defaults to FALSE
Definition at line 201 of file gdisp/options.h.
#define GDISP_NEED_TEXT_KERNING FALSE
Enable kerning for font rendering (improves character placement).
Defaults to FALSE
Definition at line 209 of file gdisp/options.h.
#define GDISP_NEED_ANTIALIAS FALSE
Enable antialiased font support.
Defaults to FALSE
Definition at line 217 of file gdisp/options.h.
#define GDISP_NEED_MULTITHREAD FALSE
Do the drawing functions need to be thread-safe.
Defaults to FALSE
Note
Both GDISP_NEED_MULTITHREAD and GDISP_NEED_ASYNC make the gdisp API thread-safe.
This is more efficient than GDISP_NEED_ASYNC as it only requires a context switch if something else is already drawing.
Definition at line 236 of file gdisp/options.h.
#define GDISP_NEED_ASYNC FALSE
Use asynchronous calls (multi-thread safe).
Defaults to FALSE
Note
Both GDISP_NEED_MULTITHREAD and GDISP_NEED_ASYNC make the gdisp API thread-safe.
Turning this on adds two context switches per transaction so it can significantly slow graphics drawing but it allows drawing operations to continue in the background.
Definition at line 248 of file gdisp/options.h.
#define GDISP_USE_CUSTOM_BOARD FALSE
Use a custom board definition even if a board definition exists.
Defaults to FALSE
If TRUE, add gdisp_lld_board.h to your project directory and customise it.
Note
Not all GDISP low level drivers currently use board definition files.
Definition at line 280 of file gdisp/options.h.
Typedef Documentation
typedef int16_t coord_t
The type for a coordinate or length on the screen.
Definition at line 35 of file gdisp.h.
typedef struct point_t point
Type for a 2D point on the screen.
typedef enum justify justify_t
Type for the text justification.
typedef enum fontmetric fontmetric_t
Type for the font metric.
typedef struct mf_font_s* font_t
The type of a font.
Definition at line 64 of file gdisp.h.
typedef enum orientation gdisp_orientation_t
Type for the screen orientation.
typedef enum powermode gdisp_powermode_t
Type for the available power modes for the screen.
typedef uint16_t color_t
The color of a pixel.
Definition at line 175 of file gdisp.h.
typedef color_t pixel_t
The type of a pixel.
Definition at line 293 of file gdisp.h.
Enumeration Type Documentation
enum justify
Type for the text justification.
Definition at line 52 of file gdisp.h.
enum fontmetric
Type for the font metric.
Definition at line 60 of file gdisp.h.
enum orientation
Type for the screen orientation.
Definition at line 68 of file gdisp.h.
enum powermode
Type for the available power modes for the screen.
Definition at line 72 of file gdisp.h.