uGFX: Mouse
Mouse
GINPUT
Detailed Description
GINPUT allows it to easily interface touchscreens and mices to your application.
Precondition
GFX_USE_GINPUT must be set to TRUE in your gfxconf.h
GINPUT_NEED_MOUSE must be set to TRUE in your gfxconf.h
Functions
void ginput_lld_mouse_init (void)
Initialise the mouse/touch.
void ginput_lld_mouse_get_reading (MouseReading *pt)
Read the mouse/touch position.
void ginputMouseWakeup (void)
Wakeup the high level code so that it attempts another read.
void ginputMouseWakeupI (void)
Wakeup the high level code so that it attempts another read.
GSourceHandle ginputGetMouse (uint16_t instance)
Creates an instance of a mouse and returns the Source handler.
bool_t ginputGetMouseStatus (uint16_t instance, GEventMouse *pmouse)
Get the current mouse position and button status.
bool_t ginputCalibrateMouse (uint16_t instance)
Performs a calibration.
void ginputSetMouseCalibrationRoutines (uint16_t instance, GMouseCalibrationSaveRoutine fnsave, GMouseCalibrationLoadRoutine fnload, bool_t requireFree)
Set the routines to store and restore calibration data.
bool_t ginputRequireMouseCalibrationStorage (uint16_t instance)
Test if a particular mouse/touch instance requires routines to save it's alibration data.
Function Documentation
void ginput_lld_mouse_init (void)
Initialise the mouse/touch.
Function Class:
Not an API, this function is for internal use only.
Referenced by ginputGetMouse().
void ginput_lld_mouse_get_reading (MouseReading * pt)
Read the mouse/touch position.
Parameters
[in] pt A pointer to the structure to fill
Note
For drivers that don't support returning a position when the touch is up (most touch devices), it should return the previous position with the new Z value. The z value is the pressure for those touch devices that support it (-100 to 100 where > 0 is touched) or, 0 or 100 for those drivers that don't.
Function Class:
Not an API, this function is for internal use only.
void ginputMouseWakeup (void)
Wakeup the high level code so that it attempts another read.
Note
This routine is provided to low level drivers by the high level code
Particularly useful if GINPUT_MOUSE_POLL_PERIOD = TIME_INFINITE
Function Class:
Not an API, this function is for internal use only.
Definition at line 571 of file mouse.c.
References gtimerJab().
void ginputMouseWakeupI (void)
Wakeup the high level code so that it attempts another read.
Note
This routine is provided to low level drivers by the high level code
Particularly useful if GINPUT_MOUSE_POLL_PERIOD = TIME_INFINITE
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Function Class:
Not an API, this function is for internal use only.
Definition at line 576 of file mouse.c.
References gtimerJabI().
GSourceHandle ginputGetMouse (uint16_t instance)
Creates an instance of a mouse and returns the Source handler.
Note
hack: if the instance is 9999, no calibration will be performed!
Parameters
[in] instance The ID of the mouse input instance (from 0 to 9999)
Returns
The source handle of the created instance
Definition at line 311 of file mouse.c.
References gfxFree(), ginput_lld_mouse_init(), ginputCalibrateMouse(), gtimerStart(), and TRUE.
bool_t ginputGetMouseStatus (uint16_t instance, GEventMouse * pmouse)
Get the current mouse position and button status.
Note
Unlinke a listener event, this status cannot record meta events such as "CLICK".
Parameters
[in] instance The ID of the mouse input instance
[in] pmouse The mouse event
Returns
FALSE on an error (eg. invalid instance)
Definition at line 365 of file mouse.c.
References FALSE, gfxSleepMilliseconds(), and TRUE.
bool_t ginputCalibrateMouse (uint16_t instance)
Performs a calibration.
Parameters
[in] instance The ID of the mouse input instance
Returns
FALSE if the driver dosen't support a calibration of if the handle is invalid
Definition at line 389 of file mouse.c.
References FALSE, gdispClear(), gdispCloseFont(), gdispFillArea(), gdispFillStringBox(), gdispGetHeight, gdispGetWidth, gdispOpenFont(), gdispSetClip(), gdispSetOrientation, gfxSleepMilliseconds(), gtimerStart(), gtimerStop(), gwinGetDefaultBgColor(), and TRUE.
Referenced by ginputGetMouse().
void ginputSetMouseCalibrationRoutines (uint16_t instance, GMouseCalibrationSaveRoutine fnsave, GMouseCalibrationLoadRoutine fnload, bool_t requireFree)
Set the routines to store and restore calibration data.
This function should be called before first calling ginputGetMouse() for a particular instance as the gdispGetMouse() routine may attempt to fetch calibration data and perform a startup calibration if there is no way to get it. If this is called after gdispGetMouse() has been called and the driver requires calibration storage, it will immediately save the data is has already obtained. The 'requireFree' parameter indicates if the fetch buffer must be free()'d to deallocate the buffer provided by the Fetch routine.
Parameters
[in] instance The ID of the mouse input instance
[in] fnsave The routine to save the data
[in] fnload The routine to restore the data
[in] requireFree ToDo
Definition at line 530 of file mouse.c.
bool_t ginputRequireMouseCalibrationStorage (uint16_t instance)
Test if a particular mouse/touch instance requires routines to save it's alibration data.
Note
Not implemented yet
Parameters
[in] instance The ID of the mouse input instance
Returns
TRUE if needed
Definition at line 559 of file mouse.c.
References FALSE, and TRUE.