uGFX: Slider
Slider
GWIN
Detailed Description
Create sliders with different styles
Precondition
GFX_USE_GWIN must be set to TRUE in your gfxconf.h
GWIN_NEED_SLIDER must be set to TRUE in your gfxconf.h
Functions
GHandle gwinSliderCreate (GSliderObject *gb, const GWidgetInit *pInit)
Create a slider window.
void gwinSliderSetRange (GHandle gh, int min, int max)
Set the slider range.
void gwinSliderSetPosition (GHandle gh, int pos)
Set the slider position.
void gwinSliderDraw_Std (GWidgetObject *gw, void *param)
Some custom slider drawing routines.
Macros
#define gwinSliderGetPosition(gh) (((GSliderObject *)(gh))->pos)
Get the current slider position.
Function Documentation
GHandle gwinSliderCreate (GSliderObject * gb, const GWidgetInit * pInit)
Create a slider window.
Returns
NULL if there is no resultant drawing area, otherwise a window handle.
Parameters
[in] gb The GSliderObject structure to initialise. If this is NULL the structure is dynamically allocated.
[in] pInit The initialization parameters to use
Note
The drawing color and the background color get set to the current defaults. If you haven't called gwinSetDefaultColor() or gwinSetDefaultBgColor() then these are White and Black respectively.
The font gets set to the current default font. If you haven't called gwinSetDefaultFont() then there is no default font and text drawing operations will no nothing.
A slider remembers its normal drawing state. If there is a window manager then it is automatically redrawn if the window is moved or its visibility state is changed.
The initial slider range is from 0 to 100 with an initial position of 0.
A slider supports mouse, toggle and dial input.
When assigning a toggle, only one toggle is supported per role. If you try to assign more than one toggle to a role it will forget the previous toggle. Two roles are supported: Role 0 = toggle for down, Role 1 = toggle for up.
When assigning a dial, only one dial is supported. If you try to assign more than one dial it will forget the previous dial. Only dial role 0 is supported.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 226 of file slider.c.
References _gwidgetCreate(), GWIDGET_NO_INSTANCE, and gwinSetVisible().
void gwinSliderSetRange (GHandle gh, int min, int max)
Set the slider range.
Parameters
[in] gh The window handle (must be a slider window)
[in] min The minimum value
[in] max The maximum value
Note
Sets the position to the minimum value.
The slider is not automatically drawn. Call gwinSliderDraw() after changing the range.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 244 of file slider.c.
void gwinSliderSetPosition (GHandle gh, int pos)
Set the slider position.
Parameters
[in] gh The window handle (must be a slider window)
[in] pos The new position
Note
If the new position is outside the slider range then the position is set to the closest end of the range.
The slider is not automatically drawn. Call gwinSliderDraw() after changing the position.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 259 of file slider.c.
void gwinSliderDraw_Std (GWidgetObject * gw, void * param)
Some custom slider drawing routines.
These function may be passed to gwinSetCustomDraw() to get different slider drawing styles
Parameters
[in] gw The widget (which must be a slider)
[in] param A parameter passed in from the user
Note
In your custom slider drawing function you may optionally call this standard functions and then draw your extra details on top.
The standard functions below ignore the param parameter except for gwinSliderDraw_Image().
The image custom draw function gwinSliderDraw_Image() uses param to pass in the gdispImage pointer. The image must be already opened before calling gwinSetCustomDraw(). The image is tiled to fill the active area of the slider. The normal colors apply to the border and inactive area and the dividing line between the active and inactive areas. No checking is done to compare the dimensions of the slider to the size of the image. Note text is drawn on top of the image.
These custom drawing routines don't have to worry about setting clipping as the framework sets clipping to the object window prior to calling these routines.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 282 of file slider.c.
References gdispDrawBox(), gdispDrawLine(), gdispDrawStringBox(), and gdispFillArea().
Macro Definition Documentation
#define gwinSliderGetPosition (gh) (((GSliderObject *)(gh))->pos)
Get the current slider position.
Returns
The slider position
Parameters
[in] gh The window handle (must be a slider window)
Note
The use of a listener to get the slider position is recommended if you want continuous updates on the slider position.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 119 of file slider.h.