uGFX: Window
Window
GWIN
Detailed Description
GWIN provides a basic window manager which allows it to easily create and destroy different windows at runtime. Each window will have it's own properties such as colors as well as it's own drawing origin.
Precondition
GFX_USE_GWIN must be set to TRUE in your gfxconf.h
Data Structures
struct GWindowObject
A window object structure.
struct GWindowInit
The structure to initialise a GWIN.
Functions
void gwinSetDefaultColor (color_t clr)
Set the default foreground color for all new GWIN windows.
color_t gwinGetDefaultColor (void)
Get the default foreground color for all new GWIN windows.
void gwinSetDefaultBgColor (color_t bgclr)
Set the default background color for all new GWIN windows.
color_t gwinGetDefaultBgColor (void)
Get the default background color for all new GWIN windows.
void gwinSetDefaultFont (font_t font)
Set the default font for all new GWIN windows.
font_t gwinGetDefaultFont (void)
Get the current default font.
GHandle gwinWindowCreate (GWindowObject *pgw, const GWindowInit *pInit)
Create a basic window.
void gwinDestroy (GHandle gh)
Destroy a window (of any type). Releases any dynamically allocated memory.
const char * gwinGetClassName (GHandle gh)
Get the real class name of the GHandle.
void gwinSetVisible (GHandle gh, bool_t visible)
Sets whether a window is visible or not.
bool_t gwinGetVisible (GHandle gh)
Gets the visibility of a window.
void gwinSetEnabled (GHandle gh, bool_t enabled)
Enable or disable a window.
bool_t gwinGetEnabled (GHandle gh)
Gets the enabled state of a window.
void gwinMove (GHandle gh, coord_t x, coord_t y)
Move a window.
void gwinResize (GHandle gh, coord_t width, coord_t height)
Resize a window.
void gwinRedraw (GHandle gh)
Redraw a window.
void gwinSetFont (GHandle gh, font_t font)
Set the current font for this window.
void gwinClear (GHandle gh)
Clear the window.
void gwinDrawPixel (GHandle gh, coord_t x, coord_t y)
Set a pixel in the window.
void gwinDrawLine (GHandle gh, coord_t x0, coord_t y0, coord_t x1, coord_t y1)
Draw a line in the window.
void gwinDrawBox (GHandle gh, coord_t x, coord_t y, coord_t cx, coord_t cy)
Draw a box in the window.
void gwinFillArea (GHandle gh, coord_t x, coord_t y, coord_t cx, coord_t cy)
Fill an rectangular area in the window.
void gwinBlitArea (GHandle gh, coord_t x, coord_t y, coord_t cx, coord_t cy, coord_t srcx, coord_t srcy, coord_t srccx, const pixel_t *buffer)
Fill an area in the window using the supplied bitmap.
void gwinDrawCircle (GHandle gh, coord_t x, coord_t y, coord_t radius)
Draw a circle in the window.
void gwinFillCircle (GHandle gh, coord_t x, coord_t y, coord_t radius)
Draw a filled circle in the window.
void gwinDrawEllipse (GHandle gh, coord_t x, coord_t y, coord_t a, coord_t b)
Draw an ellipse.
void gwinFillEllipse (GHandle gh, coord_t x, coord_t y, coord_t a, coord_t b)
Draw an filled ellipse.
color_t gwinGetPixelColor (GHandle gh, coord_t x, coord_t y)
Get the color of a pixel in the window.
void gwinDrawChar (GHandle gh, coord_t x, coord_t y, char c)
Draw a text character at the specified position in the window.
void gwinFillChar (GHandle gh, coord_t x, coord_t y, char c)
Draw a text character with a filled background at the specified position in the window.
void gwinDrawString (GHandle gh, coord_t x, coord_t y, const char *str)
Draw a text string in the window.
void gwinFillString (GHandle gh, coord_t x, coord_t y, const char *str)
Draw a text string with a filled background in the window.
void gwinDrawStringBox (GHandle gh, coord_t x, coord_t y, coord_t cx, coord_t cy, const char *str, justify_t justify)
Draw a text string verticly centered within the specified box.
void gwinFillStringBox (GHandle gh, coord_t x, coord_t y, coord_t cx, coord_t cy, const char *str, justify_t justify)
Draw a text string verticly centered within the specified filled box.
void gwinDrawPoly (GHandle gh, coord_t tx, coord_t ty, const point *pntarray, unsigned cnt)
Draw an enclosed polygon (convex, non-convex or complex).
void gwinFillConvexPoly (GHandle gh, coord_t tx, coord_t ty, const point *pntarray, unsigned cnt)
Fill a convex polygon.
gdispImageError gwinDrawImage (GHandle gh, gdispImage *img, coord_t x, coord_t y, coord_t cx, coord_t cy, coord_t sx, coord_t sy)
Draw the image.
typedef struct GWindowObject GWindowObject
A window object structure.
typedef struct GWindowInit GWindowInit
The structure to initialise a GWIN.
Macros
#define gwinGetClassID(gh) ((void *)((gh)->vmt))
Get an ID that uniquely describes the class of the GHandle.
#define gwinGetScreenX(gh) ((gh)->x)
Get the X coordinate of the window.
#define gwinGetScreenY(gh) ((gh)->y)
Get the Y coordinate of the window.
#define gwinGetWidth(gh) ((gh)->width)
Get the width of the window.
#define gwinGetHeight(gh) ((gh)->height)
Get the height of the window.
#define gwinSetColor(gh, clr) (gh)->color = (clr)
Set foreground color.
#define gwinSetBgColor(gh, bgclr) (gh)->bgcolor = (bgclr)
Set background color.
Enumerations
enum GWindowMinMax
A window's minimized, maximized or normal size.
Function Documentation
void gwinSetDefaultColor (color_t clr)
Set the default foreground color for all new GWIN windows.
Parameters
[in] clr The color to be set
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
color_t gwinGetDefaultColor (void)
Get the default foreground color for all new GWIN windows.
Returns
The current default color for all new GWIN windows
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinSetDefaultBgColor (color_t bgclr)
Set the default background color for all new GWIN windows.
Parameters
[in] bgclr The background color
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
color_t gwinGetDefaultBgColor (void)
Get the default background color for all new GWIN windows.
Returns
The current default background color for all new GWIN windows
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by ginputCalibrateMouse().
void gwinSetDefaultFont (font_t font)
Set the default font for all new GWIN windows.
Parameters
[in] font The new font to be set
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
font_t gwinGetDefaultFont (void)
Get the current default font.
Returns
The current default font
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
GHandle gwinWindowCreate (GWindowObject * pgw, const GWindowInit * pInit)
Create a basic window.
Returns
NULL if there is no resultant drawing area, otherwise a window handle.
Parameters
[in] pgw The window structure to initialize. If this is NULL the structure is dynamically allocated.
[in] pInit How to initialise the window
Note
The drawing color and the background color get set to the current defaults. If you haven't called gwinSetDefaultColor() or gwinSetDefaultBgColor() then these are White and Black respectively.
The font gets set to the current default font. If you haven't called gwinSetDefaultFont() then there is no default font and text drawing operations will no nothing.
A basic window does not save the drawing state. It is not automatically redrawn if the window is moved or its visibility state is changed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinDestroy (GHandle gh)
Destroy a window (of any type). Releases any dynamically allocated memory.
Parameters
[in] gh The window handle
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
const char* gwinGetClassName (GHandle gh)
Get the real class name of the GHandle.
Returns a string describing the object class.
Parameters
[in] gh The window
Returns
A string describing the object class.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinSetVisible (GHandle gh, bool_t visible)
Sets whether a window is visible or not.
Parameters
[in] gh The window
[in] visible Whether the window should be visible or not
Note
When a window is marked as not visible, drawing operations on the window do nothing.
When a window is marked as visible, it is not automatically redrawn as many window types don't remember their drawing state. Widgets such as Buttons, Sliders etc will be redrawn.
If there is no window manager in use, when a window is marked as not visible, nothing is done to remove the window from the screen. When there is a window manager, it is up to the window manager to handle what happens.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Referenced by gwinCheckboxCreate(), and gwinSliderCreate().
bool_t gwinGetVisible (GHandle gh)
Gets the visibility of a window.
Returns
TRUE if visible
Parameters
[in] gh The window
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinSetEnabled (GHandle gh, bool_t enabled)
Enable or disable a window.
Parameters
[in] gh The window handle
[in] enabled Enable or disable the window
Note
The window is automatically redrawn if it supports self-redrawing.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
bool_t gwinGetEnabled (GHandle gh)
Gets the enabled state of a window.
Returns
TRUE if enabled
Parameters
[in] gh The window
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinMove (GHandle gh, coord_t x, coord_t y)
Move a window.
Parameters
[in] gh The window
[in] x,y The new position (screen relative) for this window
Note
The final window position may not be the requested position. Windows are clipped to the screen area and the window manager may also affect the position.
The window is redrawn if it is visible. See the comments in gwinSetVisible() with regard to what can be redrawn and what can't.
It is up to the window manager to determine what happens with the screen area uncovered by moving the window. When there is no window manager, nothing is done with the uncovered area.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinResize (GHandle gh, coord_t width, coord_t height)
Resize a window.
Parameters
[in] gh The window
[in] width,height The new size of the window
Note
The final window size may not be the requested size. Windows are clipped to the screen area and the window manager may also affect the size.
The window is redrawn if it is visible. See the comments in gwinSetVisible() with regard to what can be redrawn and what can't.
It is up to the window manager to determine what happens with any screen area uncovered by resizing the window. When there is no window manager, nothing is done with the uncovered area.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinRedraw (GHandle gh)
Redraw a window.
Parameters
[in] gh The window
Note
This is normally never required as windows and widgets will redraw as required. Note that some windows are incapable of redrawing themselves as they don't save their drawing state.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinSetFont (GHandle gh, font_t font)
Set the current font for this window.
Parameters
[in] gh The window handle
[in] font The font to use for text functions
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinClear (GHandle gh)
Clear the window.
Note
Uses the current background color to clear the window
Parameters
[in] gh The window handle
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinDrawPixel (GHandle gh, coord_t x, coord_t y)
Set a pixel in the window.
Note
Uses the current foreground color to set the pixel
May leave GDISP clipping to this window's dimensions
Parameters
[in] gh The window handle
[in] x,y The coordinates of the pixel
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinDrawLine (GHandle gh, coord_t x0, coord_t y0, coord_t x1, coord_t y1)
Draw a line in the window.
Note
Uses the current foreground color to draw the line
May leave GDISP clipping to this window's dimensions
Parameters
[in] gh The window handle
[in] x0,y0 The start position
[in] x1,y1 The end position
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinDrawBox (GHandle gh, coord_t x, coord_t y, coord_t cx, coord_t cy)
Draw a box in the window.
Note
Uses the current foreground color to draw the box
May leave GDISP clipping to this window's dimensions
Parameters
[in] gh The window handle
[in] x,y The start position
[in] cx,cy The size of the box (outside dimensions)
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinFillArea (GHandle gh, coord_t x, coord_t y, coord_t cx, coord_t cy)
Fill an rectangular area in the window.
Note
Uses the current foreground color to fill the box
May leave GDISP clipping to this window's dimensions
Parameters
[in] gh The window handle
[in] x,y The start position
[in] cx,cy The size of the box (outside dimensions)
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinBlitArea (GHandle gh, coord_t x, coord_t y, coord_t cx, coord_t cy, coord_t srcx, coord_t srcy, coord_t srccx, const pixel_t * buffer)
Fill an area in the window using the supplied bitmap.
The bitmap is in the pixel format specified by the low level driver
Note
If GDISP_NEED_ASYNC is defined then the buffer must be static or at least retained until this call has finished the blit. You can tell when all graphics drawing is finished by gdispIsBusy() going FALSE.
May leave GDISP clipping to this window's dimensions
Parameters
[in] gh The window handle
[in] x,y The start filled area
[in] cx,cy The width and height to be filled
[in] srcx,srcy The bitmap position to start the fill from
[in] srccx The width of a line in the bitmap.
[in] buffer The pixels to use to fill the area.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinDrawCircle (GHandle gh, coord_t x, coord_t y, coord_t radius)
Draw a circle in the window.
Note
Uses the current foreground color to draw the circle
May leave GDISP clipping to this window's dimensions
Parameters
[in] gh The window handle
[in] x,y The center of the circle
[in] radius The radius of the circle
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinFillCircle (GHandle gh, coord_t x, coord_t y, coord_t radius)
Draw a filled circle in the window.
Note
Uses the current foreground color to draw the filled circle
May leave GDISP clipping to this window's dimensions
Parameters
[in] gh The window handle
[in] x,y The center of the circle
[in] radius The radius of the circle
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinDrawEllipse (GHandle gh, coord_t x, coord_t y, coord_t a, coord_t b)
Draw an ellipse.
Note
Uses the current foreground color to draw the ellipse
May leave GDISP clipping to this window's dimensions
Parameters
[in] gh The window handle
[in] x,y The center of the ellipse
[in] a,b The dimensions of the ellipse
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinFillEllipse (GHandle gh, coord_t x, coord_t y, coord_t a, coord_t b)
Draw an filled ellipse.
Note
Uses the current foreground color to draw the filled ellipse
May leave GDISP clipping to this window's dimensions
Parameters
[in] gh The window handle
[in] x,y The center of the ellipse
[in] a,b The dimensions of the ellipse
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
color_t gwinGetPixelColor (GHandle gh, coord_t x, coord_t y)
Get the color of a pixel in the window.
Returns
The color of the pixel.
Note
May leave GDISP clipping to this window's dimensions
Parameters
[in] gh The window handle
[in] x,y The position in the window
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinDrawChar (GHandle gh, coord_t x, coord_t y, char c)
Draw a text character at the specified position in the window.
Precondition
The font must have been set.
Note
Uses the current foreground color to draw the character
May leave GDISP clipping to this window's dimensions
Parameters
[in] gh The window handle
[in] x,y The position for the text
[in] c The character to draw
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinFillChar (GHandle gh, coord_t x, coord_t y, char c)
Draw a text character with a filled background at the specified position in the window.
Precondition
The font must have been set.
Note
Uses the current foreground color to draw the character and fills the background using the background drawing color
May leave GDISP clipping to this window's dimensions
Parameters
[in] gh The window handle
[in] x,y The position for the text
[in] c The character to draw
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinDrawString (GHandle gh, coord_t x, coord_t y, const char * str)
Draw a text string in the window.
Precondition
The font must have been set.
Note
Uses the current foreground color to draw the character
May leave GDISP clipping to this window's dimensions
Parameters
[in] gh The window handle
[in] x,y The position for the text
[in] str The string to draw
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinFillString (GHandle gh, coord_t x, coord_t y, const char * str)
Draw a text string with a filled background in the window.
Precondition
The font must have been set.
Note
Uses the current foreground color to draw the character and fills the background using the background drawing color
May leave GDISP clipping to this window's dimensions
Parameters
[in] gh The window handle
[in] x,y The position for the text
[in] str The string to draw
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinDrawStringBox (GHandle gh, coord_t x, coord_t y, coord_t cx, coord_t cy, const char * str, justify_t justify)
Draw a text string verticly centered within the specified box.
Precondition
The font must have been set.
Note
Uses the current foreground color to draw the character.
The specified box does not need to align with the window box
May leave GDISP clipping to this window's dimensions
Parameters
[in] gh The window handle
[in] x,y The position for the text (need to define top-right or base-line - check code)
[in] cx,cy The width and height of the box
[in] str The string to draw
[in] justify Justify the text left, center or right within the box
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinFillStringBox (GHandle gh, coord_t x, coord_t y, coord_t cx, coord_t cy, const char * str, justify_t justify)
Draw a text string verticly centered within the specified filled box.
Precondition
The font must have been set.
Note
Uses the current foreground color to draw the character and fills the background using the background drawing color
The entire box is filled. Note this box does not need to align with the window box
May leave GDISP clipping to this window's dimensions
Parameters
[in] gh The window handle
[in] x,y The position for the text (need to define top-right or base-line - check code)
[in] cx,cy The width and height of the box
[in] str The string to draw
[in] justify Justify the text left, center or right within the box
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinDrawPoly (GHandle gh, coord_t tx, coord_t ty, const point * pntarray, unsigned cnt)
Draw an enclosed polygon (convex, non-convex or complex).
Note
Uses the current foreground color.
Parameters
[in] gh The window handle
[in] tx,ty Transform all points in pntarray by tx, ty
[in] pntarray An array of points
[in] cnt The number of points in the array
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void gwinFillConvexPoly (GHandle gh, coord_t tx, coord_t ty, const point * pntarray, unsigned cnt)
Fill a convex polygon.
Doesn't handle non-convex or complex polygons.
Note
Uses the current foreground color.
Parameters
[in] gh The window handle
[in] tx,ty Transform all points in pntarray by tx, ty
[in] pntarray An array of points
[in] cnt The number of points in the array
Note
Convex polygons are those that have no internal angles. That is; you can draw a line from any point on the polygon to any other point on the polygon without it going outside the polygon. In our case we generalise this a little by saying that an infinite horizontal line (at any y value) will cross no more than two edges on the polygon. Some non-convex polygons do fit this criteria and can therefore be drawn.
This routine is designed to be very efficient with even simple display hardware.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
gdispImageError gwinDrawImage (GHandle gh, gdispImage * img, coord_t x, coord_t y, coord_t cx, coord_t cy, coord_t sx, coord_t sy)
Draw the image.
Returns
GDISP_IMAGE_ERR_OK (0) on success or an error code.
Parameters
[in] gh The window handle
[in] img The image structure
[in] x,y The window location to draw the image
[in] cx,cy The area on the screen to draw
[in] sx,sy The image position to start drawing at
Precondition
gdispImageOpen() must have returned successfully.
Note
If sx,sy + cx,cy is outside the image boundaries the area outside the image is simply not drawn.
If gdispImageCache() has been called first for this frame, this routine will draw using a fast blit from the cached frame. If not, it reads the input and decodes it as it is drawing. This may be significantly slower than if the image has been cached (but uses a lot less RAM)
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Macro Definition Documentation
#define gwinGetClassID (gh) ((void *)((gh)->vmt))
Get an ID that uniquely describes the class of the GHandle.
Parameters
[in] gh The window
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 210 of file gwin.h.
#define gwinGetScreenX (gh) ((gh)->x)
Get the X coordinate of the window.
Returns the X coordinate of the origin of the window. The coordinate is relative to the physical screen zero point.
Parameters
[in] gh The window
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 221 of file gwin.h.
#define gwinGetScreenY (gh) ((gh)->y)
Get the Y coordinate of the window.
Returns the Y coordinate of the origin of the window. The coordinate is relative to the physical screen zero point.
Parameters
[in] gh The window
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 232 of file gwin.h.
#define gwinGetWidth (gh) ((gh)->width)
Get the width of the window.
Parameters
[in] gh The window
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 241 of file gwin.h.
#define gwinGetHeight (gh) ((gh)->height)
Get the height of the window.
Parameters
[in] gh The window
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 250 of file gwin.h.
#define gwinSetColor (gh, clr) (gh)->color = (clr)
Set foreground color.
Set the color which will be used to draw
Parameters
[in] gh The window
[in] clr The color to be set
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 261 of file gwin.h.
#define gwinSetBgColor (gh, bgclr) (gh)->bgcolor = (bgclr)
Set background color.
Set the color which will be used as background
Note
gwinClear() must be called to set the background color
Parameters
[in] gh The window
[in] bgclr The background color
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 273 of file gwin.h.
Typedef Documentation
typedef struct GWindowObject GWindowObject
A window object structure.
Note
Do not access the members directly. Treat it as a black-box and use the method functions.
typedef struct GWindowInit GWindowInit
The structure to initialise a GWIN.
Note
Some gwin's will need extra parameters.
The dimensions and position may be changed to fit on the real screen.
Enumeration Type Documentation
enum GWindowMinMax
A window's minimized, maximized or normal size.
Definition at line 69 of file gwin.h.