uGFX: Checkbox
Checkbox
GWIN
Detailed Description
GWIN allows it to easily create a group of checkbox buttons.
Precondition
GFX_USE_GWIN must be set to TRUE in your gfxconf.h
GWIN_NEED_CHECKBOX must be set to TRUE in your gfxconf.h
Functions
GHandle gwinCheckboxCreate (GCheckboxObject *gb, const GWidgetInit *pInit)
Create a checkbox window.
void gwinCheckboxCheck (GHandle gh, bool_t isChecked)
Set the state of a checkbox.
bool_t gwinCheckboxIsChecked (GHandle gh)
Get the state of a checkbox.
void gwinCheckboxDraw_CheckOnLeft (GWidgetObject *gw, void *param)
Some custom checkbox drawing routines.
Function Documentation
GHandle gwinCheckboxCreate (GCheckboxObject * gb, const GWidgetInit * pInit)
Create a checkbox window.
Returns
NULL if there is no resultant drawing area, otherwise a window handle.
Parameters
[in] gb The GCheckboxObject structure to initialise. If this is NULL, the structure is dynamically allocated.
[in] pInit The initialization parameters to use
Note
The drawing color and the background color get set to the current defaults. If you haven't called gwinSetDefaultColor() or gwinSetDefaultBgColor() then these are White and Black respectively.
The font gets set to the current default font. If you haven't called gwinSetDefaultFont() then there is no default font and text drawing operations will no nothing.
A checkbox remembers its normal drawing state. If there is a window manager then it is automatically redrawn if the window is moved or its visibility state is changed.
A checkbox supports mouse and a toggle input.
When assigning a toggle, only one toggle is supported. If you try to assign more than one toggle it will forget the previous toggle. When assigning a toggle the role parameter must be 0.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 111 of file checkbox.c.
References _gwidgetCreate(), GWIDGET_NO_INSTANCE, and gwinSetVisible().
void gwinCheckboxCheck (GHandle gh, bool_t isChecked)
Set the state of a checkbox.
Parameters
[in] gh The window handle (must be a checkbox window)
[in] isChecked TRUE to set the check, FALSE to uncheck.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 122 of file checkbox.c.
References _gwidgetRedraw().
bool_t gwinCheckboxIsChecked (GHandle gh)
Get the state of a checkbox.
Returns
TRUE if the checkbox is currently checked
Parameters
[in] gh The window handle (must be a checkbox window)
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 137 of file checkbox.c.
References FALSE, and TRUE.
void gwinCheckboxDraw_CheckOnLeft (GWidgetObject * gw, void * param)
Some custom checkbox drawing routines.
These function may be passed to gwinSetCustomDraw() to get different checkbox drawing styles
Parameters
[in] gw The widget (which must be a checkbox)
[in] param A parameter passed in from the user
Note
In your custom checkbox drawing function you may optionally call this standard functions and then draw your extra details on top.
The standard functions below ignore the param parameter.
These custom drawing routines don't have to worry about setting clipping as the framework sets clipping to the object window prior to calling these routines.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 154 of file checkbox.c.
References gdispDrawBox(), gdispFillArea(), and gdispFillStringBox().